import { describe, expect, it, vi } from "vitest";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { runAction } from "../src/index";

function fakeCore(inputs: Record<string, string>) {
  const outputs: Record<string, unknown> = {};
  const failures: string[] = [];
  const secrets: string[] = [];
  return {
    outputs,
    failures,
    secrets,
    core: {
      getInput: (name: string) => inputs[name] ?? "",
      getBooleanInput: (name: string) => (inputs[name] ?? "false") === "true",
      setSecret: (value: string) => {
        secrets.push(value);
      },
      setOutput: (name: string, value: unknown) => {
        outputs[name] = value;
      },
      setFailed: (message: string) => {
        failures.push(message);
      },
      info: vi.fn(),
      warning: vi.fn(),
    },
  };
}

describe("runAction", () => {
  it("fails before work when no App credentials or PAT are supplied", async () => {
    const { core, failures } = fakeCore({});

    await runAction({ core });

    expect(failures).toEqual(["Provide either app-id + private-key, or pat."]);
  });

  it("opens a pull request and emits PR outputs in PAT mode", async () => {
    const { core, outputs } = fakeCore({
      pat: "pat-token",
      mode: "pull-request",
      "github-server-url": "https://github.com",
      "output-file": "TEAM.md",
      "state-file": ".team-contributors.jsonl",
      "columns-per-row": "2",
      ignore: "old-bot[bot],legacy",
    });
    const openPullRequest = vi.fn().mockResolvedValue({
      changed: true,
      addedLogins: ["ada"],
      promotedLogins: [],
      contributorsCount: 1,
      contributorsJson: [{ login: "ada" }],
      proposedStateFile: "{}",
      proposedOutputFile: "Ada",
      warnings: [],
      commitSha: "abc123",
      prOpened: true,
      prNumber: "12",
      prUrl: "https://github.com/smorinlabs/example/pull/12",
    });
    const createContributors = vi.fn().mockResolvedValue({ openPullRequest });

    await runAction({
      core,
      env: { GITHUB_REPOSITORY: "smorinlabs/example" },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors,
    });

    expect(openPullRequest).toHaveBeenCalledWith({
      branch: "contributors-please/update",
      base: "main",
      body: "Generated by contributors-please.",
      commitMessage: "docs: update contributors\n\n[skip ci]",
      label: "contributors-please: pending",
      skipLabeling: false,
      title: "docs: update contributors",
    });
    expect(outputs).toMatchObject({
      changed: "true",
      "added-logins": "[\"ada\"]",
      "promoted-logins": "[]",
      "contributors-count": "1",
      "token-source": "pat",
      "committer-login": "pat-user",
      "contributors-json": "[{\"login\":\"ada\"}]",
      "pr-opened": "true",
      "pr-number": "12",
      "pr-url": "https://github.com/smorinlabs/example/pull/12",
      "commit-sha": "",
    });
    expect(createContributors).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({
        committerLogin: "pat-user",
        committerEmail: "98765+pat-user@users.noreply.github.com",
        configOverrides: {
          columns_per_row: 2,
          ignore: ["old-bot[bot]", "legacy"],
          output_file: "TEAM.md",
          state_file: ".team-contributors.jsonl",
        },
      })
    );
  });

  it("masks the selected token before write-mode side effects", async () => {
    const { core, secrets } = fakeCore({
      pat: "pat-token",
      mode: "pull-request",
    });
    const openPullRequest = vi.fn().mockResolvedValue({
      changed: true,
      addedLogins: ["ada"],
      promotedLogins: [],
      contributorsCount: 1,
      contributorsJson: [{ login: "ada" }],
      proposedStateFile: "{}",
      proposedOutputFile: "Ada",
      warnings: [],
      commitSha: "abc123",
      prOpened: true,
      prNumber: "12",
      prUrl: "https://github.com/smorinlabs/example/pull/12",
    });

    await runAction({
      core,
      env: {
        GITHUB_ACTIONS: "true",
        GITHUB_REPOSITORY: "smorinlabs/example",
      },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors: vi.fn().mockResolvedValue({ openPullRequest }),
      configureGitRemote: vi.fn().mockResolvedValue(undefined),
    });

    expect(secrets).toContain("pat-token");
  });

  it("configures origin with the selected token before pull-request push", async () => {
    const { core } = fakeCore({
      pat: "pat-token",
      mode: "pull-request",
    });
    const events: string[] = [];
    const openPullRequest = vi.fn().mockImplementation(async () => {
      events.push("pull-request");
      return {
        changed: true,
        addedLogins: ["ada"],
        promotedLogins: [],
        contributorsCount: 1,
        contributorsJson: [{ login: "ada" }],
        proposedStateFile: "{}",
        proposedOutputFile: "Ada",
        warnings: [],
        commitSha: "abc123",
        prOpened: true,
        prNumber: "12",
        prUrl: "https://github.com/smorinlabs/example/pull/12",
      };
    });
    const configureGitRemote = vi.fn().mockImplementation(async () => {
      events.push("remote");
    });

    await runAction({
      core,
      env: {
        GITHUB_ACTIONS: "true",
        GITHUB_REPOSITORY: "smorinlabs/example",
      },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors: vi.fn().mockResolvedValue({ openPullRequest }),
      configureGitRemote,
    });

    expect(configureGitRemote).toHaveBeenCalledWith({
      owner: "smorinlabs",
      repo: "example",
      serverUrl: "https://github.com",
      token: "pat-token",
    });
    expect(events).toEqual(["remote", "pull-request"]);
  });

  it("uses the HTTPS_PROXY-aware fetch for PAT lookup and library GitHub calls", async () => {
    const { core } = fakeCore({
      pat: "pat-token",
      mode: "commit",
    });
    const commit = vi.fn().mockResolvedValue({
      changed: false,
      addedLogins: [],
      promotedLogins: [],
      contributorsCount: 0,
      contributorsJson: [],
      proposedStateFile: "",
      proposedOutputFile: "",
      warnings: [],
      commitSha: "",
    });
    const baseFetch = vi.fn().mockResolvedValue(
      new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
        status: 200,
      })
    );

    await runAction({
      core,
      env: {
        GITHUB_REPOSITORY: "smorinlabs/example",
        HTTPS_PROXY: "http://proxy.example:8080",
      },
      fetch: baseFetch,
      createGitHubClient: vi.fn(async config => {
        await config.fetch?.("https://api.github.com/rate_limit");
        return { serverUrl: "https://github.com" };
      }),
      createContributors: vi.fn().mockResolvedValue({ commit }),
    });

    expect(baseFetch).toHaveBeenNthCalledWith(
      1,
      "https://api.github.com/user",
      expect.objectContaining({ dispatcher: expect.anything() })
    );
    expect(baseFetch).toHaveBeenNthCalledWith(
      2,
      "https://api.github.com/rate_limit",
      expect.objectContaining({ dispatcher: expect.anything() })
    );
  });

  it("pushes commit mode changes to the current branch with the selected token", async () => {
    const { core, outputs } = fakeCore({
      pat: "pat-token",
      mode: "commit",
    });
    const events: string[] = [];
    const commit = vi.fn().mockImplementation(async () => {
      events.push("commit");
      return {
        changed: true,
        addedLogins: ["ada"],
        promotedLogins: [],
        contributorsCount: 1,
        contributorsJson: [{ login: "ada" }],
        proposedStateFile: "{}",
        proposedOutputFile: "Ada",
        warnings: [],
        commitSha: "abc123",
      };
    });
    const configureGitRemote = vi.fn().mockImplementation(async () => {
      events.push("remote");
    });
    const pushGitRef = vi.fn().mockImplementation(async () => {
      events.push("push");
    });

    await runAction({
      core,
      env: {
        GITHUB_ACTIONS: "true",
        GITHUB_REF_NAME: "main",
        GITHUB_REPOSITORY: "smorinlabs/example",
      },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors: vi.fn().mockResolvedValue({ commit }),
      configureGitRemote,
      pushGitRef,
    });

    expect(configureGitRemote).toHaveBeenCalledWith({
      owner: "smorinlabs",
      repo: "example",
      serverUrl: "https://github.com",
      token: "pat-token",
    });
    expect(pushGitRef).toHaveBeenCalledWith({ branch: "main" });
    expect(outputs).toMatchObject({
      "commit-sha": "abc123",
    });
    expect(events).toEqual(["commit", "remote", "push"]);
  });

  it("prefers a minted App token over PAT when App credentials are supplied", async () => {
    const { core, outputs } = fakeCore({
      "app-id": "12345",
      "private-key": "private-key",
      pat: "pat-token",
      mode: "commit",
    });
    const commit = vi.fn().mockResolvedValue({
      changed: false,
      addedLogins: [],
      promotedLogins: [],
      contributorsCount: 0,
      contributorsJson: [],
      proposedStateFile: "",
      proposedOutputFile: "",
      warnings: [],
      commitSha: "",
    });
    const createGitHubClient = vi.fn().mockResolvedValue({
      serverUrl: "https://github.com",
    });
    const createContributors = vi.fn().mockResolvedValue({ commit });

    await runAction({
      core,
      env: { GITHUB_REPOSITORY: "smorinlabs/example" },
      createAppToken: vi.fn().mockResolvedValue({
        token: "app-token",
        login: "contributors-please-bot[bot]",
        email:
          "12345+contributors-please-bot[bot]@users.noreply.github.com",
      }),
      createGitHubClient,
      createContributors,
    });

    expect(createGitHubClient).toHaveBeenCalledWith(
      expect.objectContaining({ token: "app-token" })
    );
    expect(outputs).toMatchObject({
      "token-source": "app",
      "committer-login": "contributors-please-bot[bot]",
    });
    expect(createContributors).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({
        committerLogin: "contributors-please-bot[bot]",
        committerEmail:
          "12345+contributors-please-bot[bot]@users.noreply.github.com",
      })
    );
  });

  it("writes a GitHub step summary when GITHUB_STEP_SUMMARY is set", async () => {
    const dir = await mkdtemp(join(tmpdir(), "contributors-action-"));
    try {
      const summaryPath = join(dir, "summary.md");
      const { core } = fakeCore({
        pat: "pat-token",
        mode: "commit",
      });
      const commit = vi.fn().mockResolvedValue({
        changed: false,
        addedLogins: [],
        promotedLogins: [],
        contributorsCount: 1,
        contributorsJson: [{ login: "ada" }],
        proposedStateFile: "",
        proposedOutputFile: "",
        warnings: ["Declared contributor `ada` had no `first_seen`; set to `2026-05-26`."],
        commitSha: "",
      });

      await runAction({
        core,
        env: {
          GITHUB_REPOSITORY: "smorinlabs/example",
          GITHUB_STEP_SUMMARY: summaryPath,
        },
        fetch: vi.fn().mockResolvedValue(
          new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
            status: 200,
          })
        ),
        createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
        createContributors: vi.fn().mockResolvedValue({ commit }),
      });

      await expect(readFile(summaryPath, "utf8")).resolves.toContain(
        "| changed | false |"
      );
      await expect(readFile(summaryPath, "utf8")).resolves.toContain(
        "Declared contributor `ada` had no `first_seen`; set to `2026-05-26`."
      );
      await expect(readFile(summaryPath, "utf8")).resolves.toContain(
        "Self-excluded committer `pat-user` from contributor classification."
      );
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("fails check mode when contributors output is stale", async () => {
    const { core, outputs, failures } = fakeCore({
      pat: "pat-token",
      mode: "check",
    });
    const check = vi.fn().mockResolvedValue({
      changed: true,
      addedLogins: ["ada"],
      promotedLogins: [],
      contributorsCount: 1,
      contributorsJson: [{ login: "ada" }],
      proposedStateFile: "{}",
      proposedOutputFile: "Ada",
      warnings: [],
      diff: "--- CONTRIBUTORS.md\n+++ CONTRIBUTORS.md\n",
    });

    await runAction({
      core,
      env: { GITHUB_REPOSITORY: "smorinlabs/example" },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors: vi.fn().mockResolvedValue({ check }),
    });

    expect(check).toHaveBeenCalledOnce();
    expect(failures).toEqual([
      "contributors-please check failed: generated files are out of date",
    ]);
    expect(outputs).toMatchObject({
      changed: "true",
      "token-source": "pat",
      "committer-login": "pat-user",
    });
  });

  it("posts a pull request comment when check mode finds a diff", async () => {
    const dir = await mkdtemp(join(tmpdir(), "contributors-action-"));
    try {
      const eventPath = join(dir, "event.json");
      await writeFile(eventPath, JSON.stringify({ pull_request: { number: 42 } }));
      const { core, failures } = fakeCore({
        pat: "pat-token",
        mode: "check",
      });
      const check = vi.fn().mockResolvedValue({
        changed: true,
        addedLogins: ["ada"],
        promotedLogins: [],
        contributorsCount: 1,
        contributorsJson: [{ login: "ada" }],
        proposedStateFile: "{}",
        proposedOutputFile: "Ada",
        warnings: [],
        diff: "--- CONTRIBUTORS.md\n+++ CONTRIBUTORS.md\n",
      });
      const upsertIssueComment = vi.fn().mockResolvedValue(undefined);

      await runAction({
        core,
        env: {
          GITHUB_REPOSITORY: "smorinlabs/example",
          GITHUB_EVENT_NAME: "pull_request",
          GITHUB_EVENT_PATH: eventPath,
        },
        fetch: vi.fn().mockResolvedValue(
          new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
            status: 200,
          })
        ),
        createGitHubClient: vi.fn().mockResolvedValue({
          serverUrl: "https://github.com",
          upsertIssueComment,
        }),
        createContributors: vi.fn().mockResolvedValue({ check }),
      });

      expect(failures).toEqual([
        "contributors-please check failed: generated files are out of date",
      ]);
      expect(upsertIssueComment).toHaveBeenCalledWith(
        42,
        expect.stringContaining("<!-- contributors-please:check-comment -->")
      );
      expect(upsertIssueComment).toHaveBeenCalledWith(
        42,
        expect.stringContaining("--- CONTRIBUTORS.md")
      );
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("does not fail or post a pull request comment in dry-run check mode", async () => {
    const dir = await mkdtemp(join(tmpdir(), "contributors-action-"));
    try {
      const eventPath = join(dir, "event.json");
      await writeFile(eventPath, JSON.stringify({ pull_request: { number: 42 } }));
      const { core, failures } = fakeCore({
        pat: "pat-token",
        mode: "check",
        "dry-run": "true",
      });
      const check = vi.fn().mockResolvedValue({
        changed: true,
        addedLogins: ["ada"],
        promotedLogins: [],
        contributorsCount: 1,
        contributorsJson: [{ login: "ada" }],
        proposedStateFile: "{}",
        proposedOutputFile: "Ada",
        warnings: [],
        diff: "--- CONTRIBUTORS.md\n+++ CONTRIBUTORS.md\n",
      });
      const upsertIssueComment = vi.fn().mockResolvedValue(undefined);

      await runAction({
        core,
        env: {
          GITHUB_REPOSITORY: "smorinlabs/example",
          GITHUB_EVENT_NAME: "pull_request",
          GITHUB_EVENT_PATH: eventPath,
        },
        fetch: vi.fn().mockResolvedValue(
          new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
            status: 200,
          })
        ),
        createGitHubClient: vi.fn().mockResolvedValue({
          serverUrl: "https://github.com",
          upsertIssueComment,
        }),
        createContributors: vi.fn().mockResolvedValue({ check }),
      });

      expect(failures).toEqual([]);
      expect(upsertIssueComment).not.toHaveBeenCalled();
      expect(core.info).toHaveBeenCalledWith(
        "[dry-run] check mode found a diff; skipped failure and PR comment"
      );
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("logs skipped commit side effects in dry-run commit mode", async () => {
    const { core } = fakeCore({
      pat: "pat-token",
      mode: "commit",
      "dry-run": "true",
    });
    const commit = vi.fn().mockResolvedValue({
      changed: true,
      addedLogins: ["ada"],
      promotedLogins: [],
      contributorsCount: 1,
      contributorsJson: [{ login: "ada" }],
      proposedStateFile: "{}",
      proposedOutputFile: "Ada",
      warnings: [],
      commitSha: "",
    });

    await runAction({
      core,
      env: { GITHUB_REPOSITORY: "smorinlabs/example" },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors: vi.fn().mockResolvedValue({ commit }),
    });

    expect(core.info).toHaveBeenCalledWith("[dry-run] skipped commit side effect");
  });

  it("logs skipped pull request side effects in dry-run pull-request mode", async () => {
    const { core } = fakeCore({
      pat: "pat-token",
      mode: "pull-request",
      "dry-run": "true",
    });
    const openPullRequest = vi.fn().mockResolvedValue({
      changed: true,
      addedLogins: ["ada"],
      promotedLogins: [],
      contributorsCount: 1,
      contributorsJson: [{ login: "ada" }],
      proposedStateFile: "{}",
      proposedOutputFile: "Ada",
      warnings: [],
      commitSha: "",
      prOpened: false,
      prNumber: "",
      prUrl: "",
    });

    await runAction({
      core,
      env: { GITHUB_REPOSITORY: "smorinlabs/example" },
      fetch: vi.fn().mockResolvedValue(
        new Response(JSON.stringify({ login: "pat-user", id: 98765 }), {
          status: 200,
        })
      ),
      createGitHubClient: vi.fn().mockResolvedValue({ serverUrl: "https://github.com" }),
      createContributors: vi.fn().mockResolvedValue({ openPullRequest }),
    });

    expect(core.info).toHaveBeenCalledWith(
      "[dry-run] skipped commit, push, label, and pull request side effects"
    );
  });
});
